name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - uses: iterative/setup-dvc@v2
    - name: 'Pull data with dvc'
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        dvc pull
    - name: 'Build the Docker image'
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
